// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: "link",
      label: "Introduction",
      href: "/",
    },
    {
      type: "category",
      label: "SDK Documentation",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "." }],
    },
  ],
};

export default sidebars;
