/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  scorm: [
    { type: "autogenerated", dirName: "." },
    {
      type: "category",
      label: "SDK Documentation",
      items: [
        {
          type: "link",
          label: "Introduction",
          href: "/sdk/",
        },
        {
          type: "link",
          label: "Platforms",
          href: "/sdk/category/platforms",
        },
        {
          type: "link",
          label: "Android Version Policy",
          href: "/sdk/android_version_details",
        },
        {
          type: "link",
          label: "FAQ",
          href: "/sdk/faq",
        },
        {
          type: "link",
          label: "Contact Us",
          href: "/sdk/contact-us",
        },
      ],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  // scorm: [
  //   "intro",
  //   {
  //     type: "category",
  //     label: "SCORM in Sharpsell",
  //     collapsible: true,
  //     collapsed: false,
  //     items: ["scorm/guidelines"],
  //   },
  // ],
};

export default sidebars;
